const jobsData = [
  {
      image: "https://picsum.photos/200/200",
      title: "Mobile App Developer",
      company: "Samsung",
      location: "Seoul",
      type: "Full-time",
      apply: "https://www.samsung.com",
      details: "<h1>Job Overview</h1> <p>We are seeking a talented Mobile App Developer to join our innovative team. Responsibilities include designing and developing mobile applications for Android and iOS platforms. If you have a passion for mobile technology, apply now!</p>",
  },
  {
      image: "https://picsum.photos/200/200",
      title: "Product Manager",
      company: "Tesla",
      location: "Palo Alto",
      type: "Full-time",
      apply: "https://www.tesla.com",
      details: "<h1>Position Details</h1> <p>Join Tesla as a Product Manager and contribute to the development and launch of groundbreaking products. Responsibilities include defining product features, conducting market research, and collaborating with cross-functional teams. Apply now to drive innovation!</p>",
  },
  {
      image: "https://picsum.photos/200/200",
      title: "AI/ML Engineer",
      company: "Adobe",
      location: "San Francisco",
      type: "Full-time",
      apply: "https://www.adobe.com",
      details: "<h1>Job Overview</h1> <p>Adobe is looking for an experienced AI/ML Engineer to join our growing team. Responsibilities include developing machine learning algorithms, implementing AI solutions, and collaborating with data scientists. If you're passionate about AI, apply now!</p>",
  },
  {
      image: "https://picsum.photos/200/200",
      title: "Cybersecurity Analyst",
      company: "Cisco",
      location: "San Jose",
      type: "Contract",
      apply: "https://www.cisco.com",
      details: "<h1>Position Details</h1> <p>As a Cybersecurity Analyst at Cisco, you will play a key role in ensuring the security of our networks and systems. Responsibilities include monitoring security incidents, analyzing threats, and implementing security measures. Join us in safeguarding digital infrastructure!</p>",
  },
  {
      image: "https://picsum.photos/200/200",
      title: "Graphic Designer",
      company: "Adobe",
      location: "San Jose",
      type: "Full-time",
      apply: "https://www.adobe.com",
      details: "<h1>Job Overview</h1> <p>Adobe is hiring a skilled Graphic Designer to create visually stunning designs for our products and marketing materials. Responsibilities include collaborating with cross-functional teams and ensuring brand consistency. Apply now to showcase your design talents!</p>",
  },
  {
      image: "https://picsum.photos/200/200",
      title: "DevOps Engineer",
      company: "Microsoft",
      location: "Redmond",
      type: "Full-time",
      apply: "https://www.microsoft.com",
      details: "<h1>Position Details</h1> <p>Join Microsoft as a DevOps Engineer to drive efficiency in software development and deployment processes. Responsibilities include implementing CI/CD pipelines, automating infrastructure, and ensuring system reliability. Apply now to be part of a dynamic DevOps team!</p>",
  },
  {
      image: "https://picsum.photos/200/200",
      title: "UX Researcher",
      company: "Google",
      location: "Mountain View",
      type: "Full-time",
      apply: "https://www.google.com",
      details: "<h1>Job Overview</h1> <p>Google is seeking a UX Researcher to conduct user research and provide valuable insights for product development. Responsibilities include designing and executing usability studies, analyzing user feedback, and collaborating with designers. Apply now to shape user experiences!</p>",
  },
  {
      image: "https://picsum.photos/200/200",
      title: "Software Architect",
      company: "Amazon",
      location: "Seattle",
      type: "Full-time",
      apply: "https://www.amazon.com",
      details: "<h1>Position Details</h1> <p>As a Software Architect at Amazon, you will play a crucial role in designing scalable and high-performance software systems. Responsibilities include defining architecture, guiding development teams, and ensuring technical excellence. Apply now to lead innovative software solutions!</p>",
  },
  {
      image: "https://picsum.photos/200/200",
      title: "Blockchain Developer",
      company: "IBM",
      location: "Armonk",
      type: "Full-time",
      apply: "https://www.ibm.com",
      details: "<h1>Job Overview</h1> <p>IBM is looking for a skilled Blockchain Developer to work on cutting-edge blockchain projects. Responsibilities include designing and implementing blockchain solutions, collaborating with cross-functional teams, and staying updated on industry trends. Apply now to be part of the blockchain revolution!</p>",
  },
  {
      image: "https://picsum.photos/200/200",
      title: "AI Ethics Specialist",
      company: "Microsoft",
      location: "Redmond",
      type: "Full-time",
      apply: "https://www.microsoft.com",
      details: "<h1>Position Details</h1> <p>Join Microsoft as an AI Ethics Specialist to ensure ethical AI practices in our products and services. Responsibilities include developing ethical guidelines, conducting impact assessments, and promoting responsible AI. Apply now to shape the future of AI with ethical considerations!</p>",
  },
  {
      image: "https://picsum.photos/200/200",
      title: "Cloud Solutions Architect",
      company: "Google",
      location: "Mountain View",
      type: "Full-time",
      apply: "https://www.google.com",
      details: "<h1>Job Overview</h1> <p>Google is hiring a Cloud Solutions Architect to design and implement cloud solutions for our clients. Responsibilities include assessing client requirements, designing scalable architectures, and providing technical expertise. Apply now to shape the future of cloud computing!</p>",
  },
  {
      image: "https://picsum.photos/200/200",
      title: "Machine Learning Engineer",
      company: "Facebook",
      location: "Menlo Park",
      type: "Full-time",
      apply: "https://www.facebook.com",
      details: "<h1>Position Details</h1> <p>As a Machine Learning Engineer at Facebook, you will work on developing and implementing machine learning models. Responsibilities include data analysis, model training, and collaborating with cross-functional teams. Apply now to contribute to innovative machine learning solutions!</p>",
  },
  {
      image: "https://picsum.photos/200/200",
      title: "Cybersecurity Consultant",
      company: "Cisco",
      location: "San Jose",
      type: "Contract",
      apply: "https://www.cisco.com",
      details: "<h1>Job Overview</h1> <p>Cisco is seeking a Cybersecurity Consultant to provide expert guidance on cybersecurity strategies. Responsibilities include conducting security assessments, developing risk mitigation plans, and advising clients on security best practices. Apply now to make a difference in cybersecurity!</p>",
  },
  {
      image: "https://picsum.photos/200/200",
      title: "AR/VR Developer",
      company: "Apple",
      location: "Cupertino",
      type: "Full-time",
      apply: "https://www.apple.com",
      details: "<h1>Position Details</h1> <p>Join Apple as an AR/VR Developer to work on cutting-edge augmented and virtual reality projects. Responsibilities include developing immersive experiences, optimizing performance, and staying updated on AR/VR technologies. Apply now to shape the future of immersive technology!</p>",
  },
  {
      image: "https://picsum.photos/200/200",
      title: "IT Project Manager",
      company: "Tesla",
      location: "Palo Alto",
      type: "Full-time",
      apply: "https://www.tesla.com",
      details: "<h1>Job Overview</h1> <p>Tesla is hiring an IT Project Manager to oversee and coordinate IT projects. Responsibilities include project planning, resource management, and ensuring successful project delivery. Apply now to lead impactful IT initiatives at Tesla!</p>",
  },
  {
      image: "https://picsum.photos/200/200",
      title: "Social Media Manager",
      company: "Facebook",
      location: "Menlo Park",
      type: "Full-time",
      apply: "https://www.facebook.com",
      details: "<h1>Position Details</h1> <p>As a Social Media Manager at Facebook, you will lead social media strategy and engagement. Responsibilities include content planning, community management, and analyzing social media metrics. Apply now to shape the social media presence of a global tech giant!</p>",
  },
  {
      image: "https://picsum.photos/200/200",
      title: "Quality Assurance Engineer",
      company: "Amazon",
      location: "Seattle",
      type: "Full-time",
      apply: "https://www.amazon.com",
      details: "<h1>Job Overview</h1> <p>Amazon is seeking a Quality Assurance Engineer to ensure the quality and reliability of our software products. Responsibilities include test planning, execution, and collaborating with development teams. Apply now to contribute to delivering high-quality software at scale!</p>",
  },
  {
      image: "https://picsum.photos/200/200",
      title: "Data Engineer",
      company: "Microsoft",
      location: "Redmond",
      type: "Full-time",
      apply: "https://www.microsoft.com",
      details: "<h1>Position Details</h1> <p>Join Microsoft as a Data Engineer to design and implement data solutions. Responsibilities include data modeling, ETL processes, and ensuring data quality. Apply now to be part of a dynamic team shaping the future of data!</p>",
  },
  {
      image: "https://picsum.photos/200/200",
      title: "UI/UX Developer",
      company: "Google",
      location: "Mountain View",
      type: "Full-time",
      apply: "https://www.google.com",
      details: "<h1>Job Overview</h1> <p>Google is hiring a UI/UX Developer to create intuitive and visually appealing user interfaces. Responsibilities include wireframing, prototyping, and collaborating with designers. Apply now to be part of creating exceptional user experiences!</p>",
  },
];

export default jobsData;
